#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xset s off &
xset -dpms &
xset s off -dpms &

xsetroot -solid "#222222" &

setxkbmap -option "grp:ctrl_shift_toggle,grp_led:scroll" -layout "us,ru" &
xsetroot -cursor_name left_ptr &
picom --vsync --detect-transient &
polybar bar &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
#bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a LXAppearance state=floating
